# Generated by Django 4.2.27 on 2026-03-31 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_trader"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trader",
            name="license_no",
        ),
    ]
