# Generated by Django 4.2.27 on 2026-03-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_trader_license_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="account_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="farmer",
            name="balance_type",
            field=models.CharField(
                choices=[("Cr", "Cr"), ("Dr", "Dr")], default="Cr", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="bank_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="farmer",
            name="branch_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="farmer",
            name="ifsc",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="farmer",
            name="opening_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="trader",
            name="account_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trader",
            name="balance_type",
            field=models.CharField(
                choices=[("Cr", "Cr"), ("Dr", "Dr")], default="Cr", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="trader",
            name="bank_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="trader",
            name="branch_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="trader",
            name="ifsc",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="trader",
            name="opening_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
