# Generated by Django 4.2.27 on 2026-03-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_farmer_account_no_farmer_balance_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trader",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="trader",
            name="gstin",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="trader",
            name="pan",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="trader",
            name="pin",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="trader",
            name="short_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
