# Generated by Django 4.2.27 on 2026-03-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_trader_email_trader_gstin_trader_pan_trader_pin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trader",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
