# Generated by Django 4.2.27 on 2026-03-31 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_trader_mobile_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avak",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("place", models.CharField(blank=True, max_length=255, null=True)),
                ("lot_number", models.CharField(max_length=100)),
                ("variety", models.CharField(blank=True, max_length=100, null=True)),
                ("no_of_bags", models.IntegerField(default=0)),
                (
                    "hamali_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "hamali_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.farmer",
                    ),
                ),
            ],
        ),
    ]
