# Generated by Django 4.2.27 on 2026-03-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_avak"),
    ]

    operations = [
        migrations.AddField(
            model_name="avak",
            name="advance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="avak",
            name="empty_bags",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="avak",
            name="freight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
