# Generated by Django 4.2.27 on 2026-04-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_avak_advance_avak_empty_bags_avak_freight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avak",
            name="lot_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
