# Generated by Django 4.2.27 on 2026-04-03 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_avak_lot_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="avak",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avak_purchases",
                to="accounts.trader",
            ),
        ),
    ]
