# Generated by Django 4.2.27 on 2026-04-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_avak_buyer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bikri",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("no_of_bags", models.IntegerField(default=0)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_weight",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "hamali",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "packing",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "avak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bikri_entries",
                        to="accounts.avak",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bikri_purchases",
                        to="accounts.trader",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BikriBagWeight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bag_no", models.IntegerField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "bikri",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="accounts.bikri",
                    ),
                ),
            ],
        ),
    ]
