# Generated by Django 4.2.27 on 2026-04-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_bikri_bikribagweight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avak",
            name="lot_number",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="avak",
            constraint=models.UniqueConstraint(
                fields=("date", "lot_number"), name="unique_lot_per_day"
            ),
        ),
    ]
