# Generated by Django 4.2.27 on 2026-04-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_avak_lot_number_avak_unique_lot_per_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "farmer_packing_per_bag",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "farmer_hamali_per_bag",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "trader_packing_per_bag",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "trader_hamali_per_bag",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "weighman_fee_per_bag",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dalali_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cess_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "gst_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("print_farmer_weights", models.BooleanField(default=False)),
                ("print_detailed_bikri_bill", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "market_rates",
            },
        ),
    ]
