# Generated by Django 4.2.27 on 2026-04-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_marketrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikri",
            name="cess",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bikri",
            name="dalali",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bikri",
            name="gst",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bikri",
            name="weighman_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
