# Generated by Django 4.2.27 on 2026-04-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_bikri_cess_bikri_dalali_bikri_gst_bikri_weighman_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikri",
            name="cash_deduct",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bikri",
            name="farmer_hamali",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bikri",
            name="farmer_packing",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bikri",
            name="net_payable",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="bikri",
            name="other_fee_1",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bikri",
            name="other_fee_2",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bikri",
            name="rent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bikri",
            name="unload_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="marketrate",
            name="farmer_unloading_per_bag",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
