# Generated by Django 4.2.27 on 2026-04-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_bikri_cash_deduct_bikri_farmer_hamali_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikri",
            name="cess_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bikri",
            name="dalali_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bikri",
            name="farmer_hamali_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bikri",
            name="farmer_packing_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bikri",
            name="farmer_unloading_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bikri",
            name="gst_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bikri",
            name="hamali_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bikri",
            name="packing_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
