# Generated by Django 4.2.27 on 2026-04-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_bikri_cess_rate_bikri_dalali_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketrate",
            name="rakham_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
