# Generated by Django 4.2.27 on 2026-04-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_marketrate_rakham_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="avak",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bikri",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
