# Generated by Django 4.2.27 on 2026-04-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_avak_is_cancelled_bikri_is_cancelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikri",
            name="farmer_name_override",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bikri",
            name="village_override",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
