# Generated by Django 4.2.27 on 2026-04-16 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_bikri_farmer_name_override_bikri_village_override"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraderBill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_no", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField()),
                ("total_bags", models.IntegerField(default=0)),
                (
                    "total_weight",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "packing",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "hamali",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "weighman_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cess",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "gst",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "round_off",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trader_bills",
                        to="accounts.trader",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TraderBillItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bikri",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.bikri"
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="accounts.traderbill",
                    ),
                ),
            ],
        ),
    ]
