# Generated by Django 4.2.27 on 2026-05-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_traderbill_traderbillitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traderbill",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="accounts.trader",
            ),
        ),
        migrations.AlterField(
            model_name="traderbill",
            name="cess",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="traderbill",
            name="commission",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="traderbill",
            name="grand_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="traderbill",
            name="gst",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="traderbill",
            name="hamali",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="traderbill",
            name="packing",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="traderbill",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="traderbill",
            name="total_weight",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="traderbill",
            name="weighman_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="traderbillitem",
            name="bikri",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.bikri"
            ),
        ),
        migrations.CreateModel(
            name="BagTransfer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("no_of_bags", models.IntegerField(default=0)),
                (
                    "total_weight",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "hamali",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "packing",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dalali",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cess",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "gst",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "weighman_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "hamali_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "packing_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dalali_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cess_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "gst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "weighman_fee_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_bikri",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_out",
                        to="accounts.bikri",
                    ),
                ),
                (
                    "target_buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_in",
                        to="accounts.trader",
                    ),
                ),
            ],
        ),
    ]
