# Generated by Django 4.2.27 on 2026-05-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_bagtransfer_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="BagTransferWeight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bag_no", models.IntegerField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="accounts.bagtransfer",
                    ),
                ),
            ],
        ),
    ]
