# Generated by Django 4.2.27 on 2026-05-09 07:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_bagtransferweight"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("Debit", "Debit"), ("Credit", "Credit")],
                        default="Debit",
                        max_length=10,
                    ),
                ),
                (
                    "person_type",
                    models.CharField(
                        blank=True,
                        choices=[("Farmer", "Farmer"), ("Trader", "Trader")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("place", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "bikri_bill_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Cheque", "Cheque"),
                            ("RTGS", "RTGS"),
                            ("NEFT", "NEFT"),
                            ("Others", "Others"),
                        ],
                        default="Cash",
                        max_length=20,
                    ),
                ),
                ("narration", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_transactions",
                        to="accounts.farmer",
                    ),
                ),
                (
                    "trader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_transactions",
                        to="accounts.trader",
                    ),
                ),
            ],
        ),
    ]
