# Generated by Django 6.0.4 on 2026-05-13 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_financialtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('nature', models.CharField(choices=[('Assets', 'Assets'), ('Liabilities', 'Liabilities'), ('Income', 'Income'), ('Expenses', 'Expenses')], max_length=20)),
            ],
            options={
                'ordering': ['nature', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_type', models.CharField(choices=[('Dr', 'Dr'), ('Cr', 'Cr')], default='Dr', max_length=2)),
                ('is_system', models.BooleanField(default=False)),
                ('farmer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_account', to='accounts.farmer')),
                ('trader', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_account', to='accounts.trader')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_accounts', to='accounts.ledgergroup')),
            ],
            options={
                'ordering': ['group__nature', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Journal', 'Journal'), ('Contra', 'Contra')], max_length=20)),
                ('voucher_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('narration', models.TextField(blank=True, null=True)),
                ('is_auto', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ref_bikri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='accounts.bikri')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('Dr', 'Debit'), ('Cr', 'Credit')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('narration', models.CharField(blank=True, max_length=500, null=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='accounts.ledgeraccount')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounts.voucher')),
            ],
        ),
    ]
