# Generated by Django 6.0.4 on 2026-05-13 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_tally_voucher_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='pay_from_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_from', to='accounts.ledgeraccount'),
        ),
    ]
