# Generated by Django 6.0.4 on 2026-05-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_financialtransaction_cheque_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='cheque_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
