# Generated by Django 6.0.4 on 2026-05-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_cheque_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='bikri_bill_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vikri Bill No'),
        ),
    ]
