# Generated by Django 6.0.4 on 2026-05-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_voucher_bikri_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikri',
            name='bill_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
